version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_sk
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null

  - name: dim_subscriptions_current
    columns:
      - name: subscription_sk
        tests:
          - not_null
          - unique

  - name: fct_invoices
    columns:
      - name: invoice_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id